### PR TITLE
Issue #201: finish style guide design.

### PR DESCRIPTION
**Pull request by ronnienorwood**
Updating style guide design for https://github.com/backdrop/backdrop-issues/issues/201 as part of rebranding the admin theme.

### CODE REVIEW

**Comment by jenlampton** [comment]
The markup in the styleguide was generated by using a Backdrop port of the [styleguide module](https://www.drupal.org/project/styleguide) so the column-formatting won't be preserved the next time we regenerate this guide.

That said, I do want to merge these changes so that we can see where we're at as far as choosing new styles. For now, this is our playground...

**Comment by ronnienorwood** [comment]
Why does the guide need to be regenerated again ??

The table looks good.
I see that the dialog js was taken out of the dialog section.  Does the dialog wrapper need to be so tall now ??

**Comment by jenlampton** [comment]
The styleguide module is a tool front-end developers use to be sure that they have styled all the elements that come out of Drupal/Backdrop "by default" so that they don't overlook something like system messages, when everything else on a site has been designed & themed.

Here, we used the styleguide module to generate a styleguide for Backdrop itself, so that we can be sure that all the interface elements from the software get a cohesive look/feel in the updated admin theme.

This version of the guide was generated months ago, and we've made some changes to the HTML & CSS in core since then. It's important that everything we have in core is also in our styleguide.  (We've added the admin_bar module, for example, and we will need to style the nav bar itself, as well as the drop-down items.)

I do think having multiple columns is a good idea, and as soon as @quicksketch adds the styleguide module to the contrib repository I'd like to recommend that you make those changes there so that we can preserve those layout changes going forward. Plus, everyone else using the styleguide module will benefit the same as us :)

**Comment by ronnienorwood** [comment]
That helps.  Sounds good.  I will plan to make the changes again after the module comes out.

**Pull request merged**
